controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    effort_controllers:
      type: effort_controllers/JointGroupEffortController
    
    velocity_controllers:
      type: velocity_controllers/JointGroupVelocityController

    position_controllers:
      type: position_controller/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
position_controllers:
  ros__parameters:
    joints: 
      - leg
    command_interface: 
      - position
    state_interface: 
      - position
      - velocity
      - effort

velocity_controllers:
  ros__parameters:
    joints: 
      - joint_wheel
      - leg
    command_interface: 
      - velocity
    state_interface: 
      - position
      - velocity
      - effort

effort_controllers:
  ros__parameters:
    joints: 
      - joint_wheel
      - leg
    command_interface: 
      - effort
    state_interface: 
      - position
      - velocity
      - effort