controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # position_controller:
    #   type: position_controllers/JointGroupPositionController
    forward_position_controller:
      type: forward_command_controller/ForwardCommandController
    effort_controllers:
      type: effort_controllers/JointGroupEffortController
    
    velocity_controllers:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
velocity_controllers:
  ros__parameters:
    joints: 
      - joint_body
      - joint_wheel
      - joint_propeller_1
      - joint_propeller_2
    command_interface: 
      - velocity
    state_interface: 
      - position
      - velocity
      - effort
      
forward_position_controller:
  ros__parameters:
    joints:
      - joint_body

    interface_name: position
# position_controller:
#   ros__parameters:
#     joints:
#       - joint_body


effort_controllers:
  ros__parameters:
    joints: 
      - joint_body
      - joint_wheel
      - joint_propeller_1
      - joint_propeller_2
    command_interface: 
      - effort
    state_interface: 
      - position
      - velocity
      - effort