imu:
  orientation: 0.0 0.0 0.0
  position: 0.0 0.0 0.027
  link: body

# lidar:
#   orientation: 0.0 0.0 0.0
#   position: 0.5 0.0 0.2
#   link: link_0
# camera:
#   orientation: 0.0 0.0 0.0
#   position: 0.0 0.0 0.0
#   link: end_effector

